"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _student_dashboard from './student-dashboard.bones.json'
import _community_feed_main from './community-feed-main.bones.json'
import _marketplace_main from './marketplace-main.bones.json'
import _canteen_main from './canteen-main.bones.json'
import _print_page_main from './print-page-main.bones.json'
import _profile_page_main from './profile-page-main.bones.json'
import _admin_dashboard_main from './admin-dashboard-main.bones.json'
import _search_page_results from './search-page-results.bones.json'
import _student_notifications from './student-notifications.bones.json'
import _professor_dashboard_main from './professor-dashboard-main.bones.json'
import _saved_bookmarks_posts from './saved-bookmarks-posts.bones.json'

registerBones({
  "student-dashboard": _student_dashboard,
  "community-feed-main": _community_feed_main,
  "marketplace-main": _marketplace_main,
  "canteen-main": _canteen_main,
  "print-page-main": _print_page_main,
  "profile-page-main": _profile_page_main,
  "admin-dashboard-main": _admin_dashboard_main,
  "search-page-results": _search_page_results,
  "student-notifications": _student_notifications,
  "professor-dashboard-main": _professor_dashboard_main,
  "saved-bookmarks-posts": _saved_bookmarks_posts,
})
