export const REPUTATION = {
  TRUSTED_MEMBER_THRESHOLD: 300,
  EARN_SELL_ITEM: 10,
  EARN_COMMUNITY_POST: 2,
  EARN_CANTEEN_RATING: 1,
  EARN_INVITE_FRIEND: 20,
  EARN_SIGNUP_BONUS: 50,
  SPEND_BOOST_LISTING: 10,
  SPEND_PIN_POST: 5,
  PENALTY_NO_SHOW: 50,
};

export const ORDER = {
  PICKUP_WINDOW_MINUTES: 20,
  SLOT_DURATION_MINUTES: 15,
  MIN_ADVANCE_MINUTES: 15,
  MAX_ADVANCE_HOURS: 2,
};

export const FILES = {
  MAX_AVATAR_SIZE_MB: 5,
  MAX_BANNER_SIZE_MB: 8,
  MAX_PDF_SIZE_MB: 50,
  MAX_LISTING_IMAGES: 5,
};

export const INVITE = {
  CODES_PER_USER: 2,
  REFRESH_HOURS: 48,
};

export const TIME = {
  MS_PER_HOUR: 60 * 60 * 1000,
  MS_PER_DAY: 24 * 60 * 60 * 1000,
};
